name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Check lint and tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install nox
        run: |
          pip install nox
      - name: Run check
        run: |
          nox --sessions check
      - name: Run test
        run: |
          nox --sessions test
